### ISSUE TITLE
Подровнять макет под стандарты

### ISSUE THREAD

**Issue by Znack** [in19farkt/FlatUI#6]
Все пункты называть не буду, но кое-где отошел от макета :)
например, h1 только один на страницу должен быть)
Или вот еще: наличие <!DOCTYPE html> в начале страницы
Или то что title идет перед charset - это может привести к косякам, если юникодовские символы там содержатся :)
ну и по остальным пунктам обязательно пройтись и их пофиксить)

**Comment by in19farkt** [comment]
Сделал
