### ISSUE TITLE
В loaders exclude лучше добавить все файлы из plugins

### ISSUE THREAD

**Issue by Znack** [in19farkt/FlatUI#7]
Потому что для новой библиотеки придется тогда менять вебпаковский конфиг)
И `noParse: /node_modules\/jquery/` скорее всего не нужен, лучше просто в exclude добавить у лоадеров

**Comment by in19farkt** [comment]
`noParse` же вроде нужен не для лоадеров, а для того чтобы вебпак не искал в этих файлах реквайры, за счет чего сборка идет немного быстрее.

В loaders exclude добавил все файлы из plugins в этом коммите [`Fixed issue #5`](https://github.com/in19farkt/FlatUI/commit/768de7d948474bc21db51b1db380d71f5cab0862)

**Comment by Znack** [comment]
О, реально, просмотрел эту опцию в документации :)
Ну тогда оставь, да
